UzduotisPraktikos/Controllers/DarbuotojoPareigasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UzduotisPraktikos.Context;

namespace UzduotisPraktikos.Controllers
{
    public class DarbuotojoPareigasController : Controller
    {
        private PraktikosDarbuotojaiEntities db = new PraktikosDarbuotojaiEntities();

        // GET: DarbuotojoPareigas
        public ActionResult Index()
        {
            var darbuotojoPareigas = db.DarbuotojoPareigas.Include(d => d.Darbuotojai).Include(d => d.Pareigo);
            return View(darbuotojoPareigas.ToList());
        }

        // GET: DarbuotojoPareigas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DarbuotojoPareiga darbuotojoPareiga = db.DarbuotojoPareigas.Find(id);
            if (darbuotojoPareiga == null)
            {
                return HttpNotFound();
            }
            return View(darbuotojoPareiga);
        }

        // GET: DarbuotojoPareigas/Create
        public ActionResult Create()
        {
            ViewBag.DarbuotojasID = new SelectList(db.Darbuotojais, "ID", "Vardas");
            ViewBag.PareigosID = new SelectList(db.Pareigos, "PareigosID", "Pavadinimas");
            return View();
        }

        // POST: DarbuotojoPareigas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PareigosID,DarbuotojasID")] DarbuotojoPareiga darbuotojoPareiga)
        {
            var res = db.Pareigos.ToList();
            if (ModelState.IsValid)
            {
                db.DarbuotojoPareigas.Add(darbuotojoPareiga);
                db.SaveChanges();
                return RedirectToAction("Index", "Darbuotojais", null);
            }

            ViewBag.DarbuotojasID = new SelectList(db.Darbuotojais, "ID", "Vardas", darbuotojoPareiga.DarbuotojasID);
            ViewBag.PareigosID = new SelectList(db.Pareigos, "PareigosID", "Pavadinimas", darbuotojoPareiga.PareigosID);
            return View(darbuotojoPareiga);
        }

        // GET: DarbuotojoPareigas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DarbuotojoPareiga darbuotojoPareiga = db.DarbuotojoPareigas.Find(id);
            if (darbuotojoPareiga == null)
            {
                return HttpNotFound();
            }
            ViewBag.DarbuotojasID = new SelectList(db.Darbuotojais, "ID", "Vardas", darbuotojoPareiga.DarbuotojasID);
            ViewBag.PareigosID = new SelectList(db.Pareigos, "PareigosID", "Pavadinimas", darbuotojoPareiga.PareigosID);
            return View(darbuotojoPareiga);
        }

        // POST: DarbuotojoPareigas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PareigosID,DarbuotojasID")] DarbuotojoPareiga darbuotojoPareiga)
        {
            if (ModelState.IsValid)
            {
                db.Entry(darbuotojoPareiga).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DarbuotojasID = new SelectList(db.Darbuotojais, "ID", "Vardas", darbuotojoPareiga.DarbuotojasID);
            ViewBag.PareigosID = new SelectList(db.Pareigos, "PareigosID", "Pavadinimas", darbuotojoPareiga.PareigosID);
            return View(darbuotojoPareiga);
        }

        // GET: DarbuotojoPareigas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DarbuotojoPareiga darbuotojoPareiga = db.DarbuotojoPareigas.Find(id);
            if (darbuotojoPareiga == null)
            {
                return HttpNotFound();
            }
            return View(darbuotojoPareiga);
        }

        // POST: DarbuotojoPareigas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DarbuotojoPareiga darbuotojoPareiga = db.DarbuotojoPareigas.Find(id);
            db.DarbuotojoPareigas.Remove(darbuotojoPareiga);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UzduotisPraktikos/Controllers/PareigoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UzduotisPraktikos.Context;

namespace UzduotisPraktikos.Controllers
{
    public class PareigoesController : Controller
    {
        private PraktikosDarbuotojaiEntities db = new PraktikosDarbuotojaiEntities();

        // GET: Pareigoes
        public ActionResult Index()
        {
            return View(db.Pareigos.ToList());
        }

        // GET: Pareigoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pareigo pareigo = db.Pareigos.Find(id);
            if (pareigo == null)
            {
                return HttpNotFound();
            }
            return View(pareigo);
        }

        // GET: Pareigoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pareigoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PareigosID,Pavadinimas")] Pareigo pareigo)
        {
            if (ModelState.IsValid)
            {
                db.Pareigos.Add(pareigo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pareigo);
        }

        public ActionResult DarbuotojoPareigos(int id)
        {
            var res = db.DarbuotojoPareigas.ToList();
            var red = db.Pareigos.ToList();
            List<Pareigo> pareigos = new List<Pareigo>();
            foreach (var item in res)
            {
                if (item.DarbuotojasID == id)
                {
                    foreach (var items in red)
                    {
                        if (item.PareigosID == items.PareigosID)
                        {
                            pareigos.Add(items);
                        }
                    }
                }
            }
            return View("Index", pareigos);
        }

        // GET: Pareigoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pareigo pareigo = db.Pareigos.Find(id);
            if (pareigo == null)
            {
                return HttpNotFound();
            }
            return View(pareigo);
        }

        // POST: Pareigoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PareigosID,Pavadinimas")] Pareigo pareigo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pareigo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pareigo);
        }
        public ActionResult PareigosPriskyrimas()
        {
            return View();
        }
        // GET: Pareigoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pareigo pareigo = db.Pareigos.Find(id);
            if (pareigo == null)
            {
                return HttpNotFound();
            }
            return View(pareigo);
        }

        // POST: Pareigoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pareigo pareigo = db.Pareigos.Find(id);
            db.Pareigos.Remove(pareigo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UzduotisPraktikos/Views/Pareigoes/Create.cshtml
@model UzduotisPraktikos.Context.Pareigo

@{
    ViewBag.Title = "Create";
}

<h2>Sukurti</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pareiga</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sukurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Gryzti i sarasa", "Index", "Pareigoes")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UzduotisPraktikos/Views/Pareigoes/Delete.cshtml
@model UzduotisPraktikos.Context.Pareigo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pareigo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UzduotisPraktikos/Views/Pareigoes/Details.cshtml
@model UzduotisPraktikos.Context.Pareigo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pareigo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pavadinimas)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PareigosID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UzduotisPraktikos/Views/Pareigoes/Edit.cshtml
@model UzduotisPraktikos.Context.Pareigo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pareigo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PareigosID)

        <div class="form-group">
            @Html.LabelFor(model => model.Pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UzduotisPraktikos/Views/Pareigoes/Index.cshtml
@model IEnumerable<UzduotisPraktikos.Context.Pareigo>

@{
    ViewBag.Title = "Pareigos";
}

<h2>Pareigos</h2>


<p>
    @Html.ActionLink("Nauja Pareiga", "Create") |
    @Html.ActionLink("Visos Pareigos", "Index") |
    @Html.ActionLink("Priskirti Pareigas", "Create", "DarbuotojoPareigas")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Pavadinimas)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Pavadinimas)
        </td>
        <td>
        </td>
    </tr>
}

</table>